name: PR Notifier

on:
  schedule:
    - cron: "0 12 * * *" # 09:00 Brasil (UTC-3)
  workflow_dispatch:

jobs:
  check-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node scripts/check-prs.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOS: "Fernandafmsf/laravel-ci-lab"
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}

        #   ELEMENT_WEBHOOK_URL: ${{ secrets.ELEMENT_WEBHOOK_URL }}